;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #222a36
foreground = #babdc9
sep = #82848c

white = #FFFFFF
black = #000000
red = #e0259e
pink = #e0259e
purple = #8339e2
blue = #3071e1
cyan = #51aee6
teal = #00B19F
green = #61C766
lime = #B9C244
yellow = #FDD835
amber = #e75d5d
orange = #e75d5d
brown = #AC8476
indigo = #6C77BB
gray = #82848c
blue-gray = #222a36

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
